// priceConfig.js (或 .ts)
export const PRICE_CONFIG = [
    {
      type: "Studio",
      bedrooms: 0,
      bathrooms: 1,
      livingrooms: 0,
      basePrice: 170,
      steamPrice: 220,
    },
    {
      type: "1B1B1L",
      bedrooms: 1,
      bathrooms: 1,
      livingrooms: 1,
      basePrice: 200,
      steamPrice: 280,
    },
    {
      type: "2B1B1L",
      bedrooms: 2,
      bathrooms: 1,
      livingrooms: 1,
      basePrice: 240,
      steamPrice: 360,
    },
    {
      type: "2B2B1L",
      bedrooms: 2,
      bathrooms: 2,
      livingrooms: 1,
      basePrice: 280,
      steamPrice: 400,
    },
    {
      type: "3B1B1L",
      bedrooms: 3,
      bathrooms: 1,
      livingrooms: 1,
      basePrice: 320,
      steamPrice: 450,
    },
    {
      type: "3B2B1L",
      bedrooms: 3,
      bathrooms: 2,
      livingrooms: 1,
      basePrice: 360,
      steamPrice: 500,
    },
    {
      type: "4B2B1L",
      bedrooms: 4,
      bathrooms: 2,
      livingrooms: 1,
      basePrice: 400,
      steamPrice: 590,
    },
    {
      type: "4B3B1L",
      bedrooms: 4,
      bathrooms: 3,
      livingrooms: 1,
      basePrice: 450,
      steamPrice: 600,
    },
    {
      type: "5B2B1L",
      bedrooms: 5,
      bathrooms: 2,
      livingrooms: 1,
      basePrice: 450,
      steamPrice: 600,
    },
    {
      type: "5B3B1L",
      bedrooms: 5,
      bathrooms: 3,
      livingrooms: 1,
      basePrice: 500,
      steamPrice: 650,
    },
  ];
  