export type Property = {
  property_id?: number;
  user_id: string;
  address: string;
  bedrooms: number;
  bathrooms: number;
  living_rooms: number;
  pet_cleaning: boolean;
  carpet_cleaning: boolean;
  range_hood_cleaning: boolean;
  oven_cleaning: boolean;
  dishwasher_cleaning: boolean;
  entry_method: string;
  unit_number?: string;
  street_number: string;
  street_name: string;
  suburb: string;
  state: string;
  postal_code: string;
  latitude?: number;
  longitude?: number;
};
